### ISSUE TITLE
Harden Permissions by default

### ISSUE THREAD

**Issue by trytomakeyouprivate** [flathub/org.kde.okular#300]
There is no reason for Okular to have any filesystem permissions

Its save and open actions use portals so it works! 

Also having internet permissions as well as filesystem permissions (whole filesystem!!!!) is critically stupid. No app should have these permissions

I have no idea of flatpak manifests but just remove the permissions. I have never had Okular make any sound, so soundserver permissions could go too.

**Comment by travier** [comment]
- The [README](https://github.com/flathub/org.kde.okular#readme) currently mentions that host filesystem access is needed for drag & drop support. If you can confirm that this is not needed anymore for that then we could remove it. See: https://github.com/flathub/org.kde.okular/pull/34

From https://github.com/flathub/org.kde.okular/pull/55:
- Playing sounds is needed for some format support: https://okular.kde.org/formats/
- Network access so that we can open URLs.

> is critically stupid

This is not the correct tone to report issues.
